# Generated by Django 4.2.4 on 2023-08-02 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default='Default Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='Default Lecture', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentsOnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students on Course',
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ProfessorsOnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Professors on Course',
                'unique_together': {('course', 'professor')},
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='professor_id',
            field=models.ManyToManyField(related_name='professor_courses', through='courses.ProfessorsOnCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='student_id',
            field=models.ManyToManyField(related_name='student_courses', through='courses.StudentsOnCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
