# Generated by Django 4.2.4 on 2023-08-06 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_remove_courses_name_remove_courses_students_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsoncourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentsoncourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentsoncourse',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='student_id',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='professors',
            field=models.ManyToManyField(related_name='professor_courses', to=settings.AUTH_USER_MODEL, verbose_name='professors_on_course'),
        ),
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='student_courses', to=settings.AUTH_USER_MODEL, verbose_name='students_on_course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProfessorsOnCourse',
        ),
        migrations.DeleteModel(
            name='StudentsOnCourse',
        ),
    ]
